/* Citazioni del giorno (dal documento "Elenco di citazioni (trash) del giorno").
   script.js ne mostra una al giorno, a caso, e cambia a mezzanotte (ora di Roma). */
window.CITAZIONI = [
  "C’è LA CHIUSURA DEL CLAN - FIGA [SPACCHIAMO TUTTO] SI FA / I TACCHINI SE NON VIENI STASERA [NON SEI NESSUNO], C’è FABRIZZIO MAURIZZIO / FIGA",
  "CIAO>>UN ATTIMO CHE ATTRAVERSO LA STRADA / SE MI PRENDE UNA MACCHINA - A - aaaaaaa - AIUTO / ODDIO / AaAaAa [ODDIO] ùù",
  "PIJATELO PIJATELO [QUELLO/QUELLO] PIJATELO - quello là. pijatelo pijalo",
  "MI DEVI DARE [DUE MILIONI DI / EURO] DUE MILIONI DI EURO [MI DEVI DARE / CASH]",
  "L’ABBIAMO CONTROLLATO / CENTIMETRO PER CENTIMETRO - è PERFETTO E NON VOGLIO SENTIRE [ALESSANDRO è GRANDE / ALESSANDRO è TROPPO PICCOLO / ALESSANDRO – METTILO DA PARTE / QUESTA è STORIA E CULTURA.",
  "QUESTA VOLTA LO DEVO DIRE - DEVO FARE NOMI E COGNOMI [LO STANNO RIPETENDO DALLA SCORSA NOTTE, PER TUTTE QUESTE / ORE] NON è ASSOLUTAMENTE COSì <QUESTO GOVERNO NON LAVORA COL FAVORE DELLE TENEBRE>",
  "AMICI IN ASCOLTO, UN CORDIALE BUONGIORNO QUELLA DI IERI è SS [COS’è / CHE è CADUTO DALL’ALTRA PARTE, DIO !",
  "HO SCRITTO [HOT VOLEVO] FARE [HOTCHOCOLATE] è USCITO [HOT] è USCITO / DI TUTTO IO NON ASPETTAVO MAI PIù - VIDEO (èè) EFFUSIONI HOT MILF DUEMILA",
  "VERGOGNA",
  "BUONGIORNO GIOSUè, SCUSA IL DISTURBO [MA SI è STACCATO COMPLETAMENTE IL PALO DELLA LU] PIANO / SIGNORA SIGNORA NO, NIENTE / VA BE COME NON DETTO",
  "SEMPRE CARO MI FU? QUEST’ERMO COLLE? E QUESTA SIEPE? CHE DA TANTE PARTI DELL’ULTIMO ORIZZONTE IL GUARDO ESCLUDE ? [IO] NEL PENSIER / MI FINGO.",
  "TRENTASEI [COME FA A FAR DICIOTTO PIù QUINDICI NON FA] TRENTASEI / DIO TI MALEDICA.",
  "SONO UN NANO IO / SONO ALTO 1.55 / BASSO QUANTO UN NANO / SONO PRATICAMENTE / UN NANO"
];
