/* Testi in esperanto (lingue.js): testo italiano -> HTML in esperanto.
   Traduzione da far rivedere a chi parla esperanto. */
window.LINGUE_EO = {
 "← Indietro": "← Reen",
 "Bar Croazia · Bologna": "Bar Croazia · Bolonjo",
 "Eventi passati": "Pasintaj eventoj",
 "Le serate organizzate finora. Clicca su un evento per vedere tutte le foto della serata.": "La vesperoj organizitaj ĝis nun. Alklaku eventon por vidi ĉiujn fotojn de la vespero.",
 "La setta dei poeti che rinasce a Primavera": "La sekto de poetoj, kiu renaskiĝas printempe",
 "Venerdì di Repubblica": "Venerdì di Repubblica",
 "27 Marzo 2026": "27 marto 2026",
 "La poesia riempie la Piazza": "La poezio plenigas la placon",
 "30 Maggio 2026": "30 majo 2026",
 "Dicono di noi": "Oni parolas pri ni",
 "Tutti gli articoli e i servizi su Bar Croazia.": "Ĉiuj artikoloj kaj raportoj pri Bar Croazia.",
 "2 Dicembre 2025": "2 decembro 2025",
 "Non Mi Capisci - Radio 24": "Vi ne komprenas min - Radio 24",
 "Ottobre 2025": "Oktobro 2025",
 "Il rito collettivo della poesia in piazza Santo Stefano": "La kolektiva rito de poezio en placo Santo Stefano",
 "Tutte le fanzine": "Ĉiuj fanzinoj",
 "L’elenco completo dei numeri usciti finora. Clicca su un numero per leggere qualche informazione in più.": "La kompleta listo de la numeroj eldonitaj ĝis nun. Alklaku numeron por legi iom pli da informoj.",
 "Fanzine n.0": "Fanzino n.0",
 "Lunedì 22 settembre 2025 · Bologna": "Lundo, 22 septembro 2025 · Bolonjo",
 "Interventi di": "Kontribuoj de",
 "Foto di": "Fotoj de",
 "A cura di": "Redaktita de",
 "Acquista": "Aĉetu",
 "Fanzine n.1": "Fanzino n.1",
 "Lunedì 20 ottobre 2025 · Bologna": "Lundo, 20 oktobro 2025 · Bolonjo",
 "Fanzine n.2": "Fanzino n.2",
 "Lunedì 24 novembre 2025 · Bologna": "Lundo, 24 novembro 2025 · Bolonjo",
 "Fanzine n.3": "Fanzino n.3",
 "Martedì 20 gennaio 2026 · Bologna": "Mardo, 20 januaro 2026 · Bolonjo",
 "Fanzine n.4": "Fanzino n.4",
 "Lunedì 27 aprile 2026 · Bologna": "Lundo, 27 aprilo 2026 · Bolonjo",
 "Illustrazioni di": "Ilustraĵoj de",
 "Fanzine n.5": "Fanzino n.5",
 "Lunedì 22 giugno 2026 · Bologna": "Lundo, 22 junio 2026 · Bolonjo",
 "Bologna": "Bolonjo",
 "Oroscopo di Paolo Fox": "Horoskopo de Paolo Fox",
 "Radio Croazia": "Radio Croazia",
 "Sasso": "Ŝtono",
 "Scopri poeta": "Malkovru poeton",
 "Manifesto": "Manifesto",
 "L’infinito": "La senfino",
 "Meteo città": "Vetero en la urbo",
 "Eventi": "Eventoj",
 "Chi siamo": "Pri ni",
 "Fanzine": "Fanzino",
 "Open call": "Malferma alvoko",
 "Archivio": "Arkivo",
 "Canale Telegram": "Telegram-kanalo",
 "Martedì 6 ottobre 2026": "Mardo, 6 oktobro 2026",
 "Farm, Bologna": "Farm, Bolonjo",
 "Poetry Slam round I – Bar Croazia x Farm": "Poetry Slam, unua rondo – Bar Croazia x Farm",
 "Farm e Bar Croazia presentano il primo round del torneo di Poetry Slam!": "Farm kaj Bar Croazia prezentas la unuan rondon de la Poetry Slam-turniro!",
 "Parteciperanno a questa data:": "Partoprenos en ĉi tiu dato:",
 "Presentano Sofia Zoli e Nicole Venturi": "Prezentas Sofia Zoli kaj Nicole Venturi",
 "Poetry Slam valido per il campionato L.I.P.S. e sostenuto da Emilia Romagna Poetry Slam.Ingresso libero e gratuito.": "Poetry Slam valida por la ĉampioneco L.I.P.S. kaj subtenata de Emilia Romagna Poetry Slam.<br>Libera kaj senpaga eniro.",
 "Lunedì 5 e 12 ottobre 2026": "Lundoj, 5 kaj 12 oktobro 2026",
 "Piazza Santo Stefano": "Placo Santo Stefano",
 "Bologna, ore 20.30": "Bolonjo, je la 20.30",
 "Raw Poetry – nuova stagione, ottobre 2026 parte 1": "Raw Poetry – nova sezono, oktobro 2026, unua parto",
 "Riparte Raw Poetry, ogni lunedì in Piazza Santo Stefano: gare e Open Mic di poesia!": "Raw Poetry rekomencas, ĉiun lundon en la placo Santo Stefano: konkursoj kaj Open Mic de poezio!",
 "Ospiti di lunedì 5 ottobre:": "Gastoj de lundo, 5 oktobro:",
 "Giuria di Vincenzo Bosco, Marshall + 1 dal pubblico": "Ĵurio: Vincenzo Bosco, Marshall + 1 el la publiko",
 "Ospiti di lunedì 12 ottobre:": "Gastoj de lundo, 12 oktobro:",
 "Giuria di Gennaro Màdera, Robbè + 1 dal pubblico": "Ĵurio: Gennaro Màdera, Robbè + 1 el la publiko",
 "Iscrizioni in loco alle 20.30 con almeno 5 testi, fino a 12 partecipanti.Ingresso libero e gratuito.": "Aliĝo surloke je la 20.30 kun almenaŭ 5 tekstoj, ĝis 12 partoprenantoj.<br>Libera kaj senpaga eniro.",
 "Scopri di più su Instagram": "Pli sur Instagram",
 "Prossimo evento>>": "Sekva evento&gt;&gt;",
 "Bar CroaziaMovimento di poesia con poeti vivi": "Bar Croazia<br>Movado de poezio kun vivaj poetoj",
 "Bar Croazia è un progetto di poesia underground su Bologna, che organizza Poetry Slam, eventi di divulgazione letteraria, collaborazioni con tante realtà giovani del territorio e soprattutto Raw Poetry, format di poesia che si svolge ogni lunedì in Piazza Santo Stefano dal 2024.": "<span class=\"o\">Bar Croazia estas subtera poezia projekto</span> en Bolonjo, kiu organizas Poetry Slam, eventojn de literatura popularigo, kunlaborojn kun multaj junaj lokaj grupoj kaj precipe Raw Poetry, poezian formaton, kiu okazas ĉiun lundon en la placo Santo Stefano ekde 2024.",
 "Crediamo nell’inclusione attraverso la poesia, e cerchiamo di raggiungere questo obiettivo tramite l’organizzazione di eventi gratuiti e a libera partecipazione, oltre alla creazione di una fanzine autoprodotta con interventi di chiunque voglia farne parte.": "Ni kredas je inkluzivo per poezio, kaj ni celas ĝin per senpagaj kaj libere alireblaj eventoj, kaj per memeldonita fanzino kun kontribuoj de ĉiu, kiu volas partopreni.",
 "Fanzine di Bar Croazia": "Fanzino de Bar Croazia",
 "Fanzine N.0 contiene interventi di Isidoro Concas, Francesco Terzi, Sofia Zoli, Giuseppe Armillotta, Claudio Palumbo, Ilaria Sofia Parisi e foto di Cecilia Romano e Dante Farricella.A cura di Nicole Venturi e Sofia Zoli": "La fanzino N.0 enhavas kontribuojn de <span class=\"o\">Isidoro Concas, Francesco Terzi, Sofia Zoli, Giuseppe Armillotta, Claudio Palumbo, Ilaria Sofia Parisi kaj fotojn de Cecilia Romano kaj Dante Farricella.</span><br><span class=\"o\">Redaktita de Nicole Venturi kaj Sofia Zoli</span>",
 "Ordinando qui la tua copia, riceverai le istruzioni per stamparla direttamente in casa con una normalissima fotocopiatrice – o nella tua copisteria di fiducia!": "Mendante ĉi tie vian ekzempleron, vi ricevos la instrukciojn por presi ĝin rekte hejme per tute ordinara fotokopiilo – aŭ en via fidinda kopiejo!",
 "Fanzine N.1 contiene interventi di Emilia Todaro, Mario Falato, Francesca Fiori, Chiara Acri, Nina Raggi e foto di Andrea Bellaroto e Cecilia Romano.A cura di Nicole Venturi e Sofia Zoli": "La fanzino N.1 enhavas kontribuojn de <span class=\"o\">Emilia Todaro, Mario Falato, Francesca Fiori, Chiara Acri, Nina Raggi kaj fotojn de Andrea Bellaroto kaj Cecilia Romano.</span><br><span class=\"o\">Redaktita de Nicole Venturi kaj Sofia Zoli</span>",
 "Fanzine N.2 contiene interventi di Nina Sharms, Manuela Morara, Gennaro Màdera, Benedetta Colombo e foto di Cecilia Romano.A cura di Nicole Venturi e Sofia Zoli": "La fanzino N.2 enhavas kontribuojn de <span class=\"o\">Nina Sharms, Manuela Morara, Gennaro Màdera, Benedetta Colombo kaj fotojn de Cecilia Romano.</span><br><span class=\"o\">Redaktita de Nicole Venturi kaj Sofia Zoli</span>",
 "Fanzine N.3 contiene interventi di Diavoli, Francesca Fiori, Lorenzo Milite, Tommaso Virga e foto di Cecilia Romano.A cura di Nicole Venturi e Sofia Zoli": "La fanzino N.3 enhavas kontribuojn de <span class=\"o\">Diavoli, Francesca Fiori, Lorenzo Milite, Tommaso Virga kaj fotojn de Cecilia Romano.</span><br><span class=\"o\">Redaktita de Nicole Venturi kaj Sofia Zoli</span>",
 "Fanzine N.4 contiene interventi di Lorenzo Pauri, Giulia Morini, Nicole Venturi, Chiara Pinesi, Francesca Lepiane e foto di Cecilia Romano e Valentina Pocaterra.illustrazioni di Carlotta Cardillo e Sole BenedettiniA cura di Nicole Venturi e Sofia Zoli": "La fanzino N.4 enhavas kontribuojn de <span class=\"o\">Lorenzo Pauri, Giulia Morini, Nicole Venturi, Chiara Pinesi, Francesca Lepiane kaj fotojn de Cecilia Romano kaj Valentina Pocaterra.<br>ilustraĵoj de Carlotta Cardillo kaj Sole Benedettini</span><br><span class=\"o\">Redaktita de Nicole Venturi kaj Sofia Zoli</span>",
 "Fanzine N.5 contiene interventi di Sofia Caruso, Tommaso Virga, Michele Marmo, Simòn Ramirez Contreras, Giuseppe Piccolo e foto di Cecilia Romano.illustrazioni di Marzio MarianiA cura di Nicole Venturi e Sofia Zoli": "La fanzino N.5 enhavas kontribuojn de <span class=\"o\">Sofia Caruso, Tommaso Virga, Michele Marmo, Simòn Ramirez Contreras, Giuseppe Piccolo kaj fotojn de Cecilia Romano.<br>ilustraĵoj de Marzio Mariani</span><br><span class=\"o\">Redaktita de Nicole Venturi kaj Sofia Zoli</span>",
 "Prossimo numero >": "Sekva numero &gt;",
 "Invia un articolo": "Sendu artikolon",
 "Ottieni una copia": "Akiru ekzempleron",
 "Open call poetry slam": "Malferma alvoko: poetry slam",
 "Entro il 15 novembre": "Ĝis la 15-a de novembro",
 "Da ottobre parte un nuovo torneo di Poetry Slam con FARM, in via Sant’Isaia 57/D. Candidati per il III round di martedì 1 dicembre 2026, alle 20.30.": "Ekde oktobro komenciĝas nova <span class=\"o\">Poetry Slam-turniro</span> kun FARM, en via Sant’Isaia 57/D. Kandidatiĝu por la <span class=\"o\">tria rondo de mardo, 1 decembro 2026</span>, je la 20.30.",
 "Sei performer, tre minuti a testa, solo corpo e voce e testi originali: le due migliori vanno alla finale di torneo del 19 gennaio 2027. Candidature entro il 15 novembre.": "Ses prezentantoj, po tri minutoj, nur korpo kaj voĉo kaj originalaj tekstoj: la du plej bonaj iras al la turnira finalo de la 19-a de januaro 2027. Kandidatiĝoj ĝis la 15-a de novembro.",
 "Open call fanzine": "Malferma alvoko: fanzino",
 "Entro il 5 novembre": "Ĝis la 5-a de novembro",
 "Da ottobre 2026 ricominciano le uscite mensili della fanzine di Bar Croazia: raccogliamo articoli, riflessioni, illustrazioni e foto degli eventi.": "Ekde oktobro 2026 rekomenciĝas la monataj eldonoj de la <span class=\"o\">fanzino</span> de Bar Croazia: ni kolektas <span class=\"o\">artikolojn, pripensojn, ilustraĵojn kaj fotojn</span> de la eventoj.",
 "Invia la tua proposta a barcroaziabologna@gmail.com con oggetto “Fanzine Bar Croazia”, con il tuo nome, una breve biografia e il tuo contributo.": "Sendu vian proponon al <span class=\"o\">barcroaziabologna@gmail.com</span> kun la temo “Fanzine Bar Croazia”, kun via nomo, mallonga biografio kaj via kontribuo.",
 "Scopri di più": "Pli da informoj",
 "Invia la candidatura": "Sendu kandidatiĝon",
 "Prossima call>": "Sekva alvoko&gt;",
 "Tutte le foto dal 2025": "Ĉiuj fotoj ekde 2025",
 "Vedi tutte le foto >": "Vidu ĉiujn fotojn &gt;",
 "30 maggio 2026": "30 majo 2026",
 "27 marzo 2026": "27 marto 2026",
 "2 dicembre 2025": "2 decembro 2025",
 "Vedi tutto >": "Vidu ĉion &gt;",
 "Ultime cose": "Lastaj aferoj",
 "Contattaci": "Kontaktu nin",
 "Collabora con noi": "Kunlaboru kun ni",
 "Dove siamo": "Kie ni estas",
 "Contatti": "Kontaktoj",
 "Un reading nel tuo bar? Una serata di poesia? Un evento, una performance o qualcosa che non sappiamo ancora come chiamare? Scrivici. Ci piacciono le idee strane, i progetti condivisi e le occasioni per portare la poesia in posti nuovi.": "Ĉu legado en via drinkejo? Ĉu poezia vespero? Ĉu evento, prezentado aŭ io, kion ni ankoraŭ ne scias kiel nomi?<br> Skribu al ni. Ni ŝatas strangajn ideojn, komunajn projektojn kaj okazojn porti poezion al novaj lokoj.",
 "Via Santo Stefano 24, Bologna · ci trovi lì tutti i lunedì alle 20:30": "Via Santo Stefano 24, Bolonjo · vi trovos nin tie ĉiun lundon je la 20:30",
 "Apri su Google Maps": "Malfermu en Google Maps",
 "Uscite mensili da ottobre 2026": "Monataj eldonoj ekde oktobro 2026",
 "I uscita: entro il 5 ottobre 2026": "Unua eldono: ĝis la 5-a de oktobro 2026",
 "II uscita: entro il 5 novembre 2026": "Dua eldono: ĝis la 5-a de novembro 2026",
 "OPEN CALL FANZINE": "MALFERMA ALVOKO: FANZINO",
 "Da ottobre 2026 ricominciano le uscite mensili della nostra fanzine! Da quasi un anno, con Bar Croazia, oltre agli eventi, produciamo una fanzine cartacea che contiene contributi letterari e artistici sempre nuovi.": "Ekde oktobro 2026 rekomenciĝas la monataj eldonoj de nia fanzino! De preskaŭ unu jaro, kun Bar Croazia, krom la eventoj, ni produktas paperan fanzinon kun ĉiam novaj literaturaj kaj artaj kontribuoj.",
 "Vuoi inviarci la tua proposta per la fanzine?Raccogliamo articoli e riflessioni a tema letterario, illustrazioni e fotografie degli eventi.": "<strong>Ĉu vi volas sendi al ni vian proponon por la fanzino?</strong><br>Ni kolektas artikolojn kaj pripensojn pri literaturo, ilustraĵojn kaj fotojn de la eventoj.",
 "Se vuoi mandare la tua proposta puoi inviarci una mail a barcroaziabologna@gmail.com, specificando nell’oggetto “FANZINE BAR CROAZIA”.": "Se vi volas sendi vian proponon, skribu al ni retleteron al <a href=\"mailto:barcroaziabologna@gmail.com?subject=FANZINE%20BAR%20CROAZIA\">barcroaziabologna@gmail.com</a>, indikante en la temo “FANZINE BAR CROAZIA”.",
 "Nella mail ricordati di inserire:": "En la retletero memoru meti:",
 "nome e cognome (o nome d’arte);": "nomon kaj familian nomon (aŭ artistan nomon);",
 "una breve biografia;": "mallongan biografion;",
 "il tuo numero di telefono;": "vian telefonnumeron;",
 "due foto dove sei venuta bene!": "du fotojn, en kiuj vi aspektas bone!",
 "Inoltre,": "Krome,",
 "articoli e riflessioni in formato Word;": "<strong>artikolojn kaj pripensojn en formato Word;</strong>",
 "fotografie e illustrazioni in allegato, oppure tramite link (che rimandi a un Dropbox, Drive o WeTransfer).": "<strong>fotojn kaj ilustraĵojn kunsendite, aŭ per ligilo</strong> (al Dropbox, Drive aŭ WeTransfer).",
 "Per qualsiasi domanda, scrivici alla mail barcroaziabologna@gmail.com oppure nei DM su Instagram.": "Por ajna demando, skribu al ni ĉe <a href=\"mailto:barcroaziabologna@gmail.com\">barcroaziabologna@gmail.com</a> aŭ per privata mesaĝo en <a href=\"https://www.instagram.com/barcroazia/\" rel=\"noopener\" target=\"_blank\">Instagram</a>.",
 "Vuoi sostenere il progetto?Finora sono disponibili 6 numeri, che puoi ottenere in forma cartacea tramite una donazione in loco oppure in formato pdf tramite il link in bio (ko-fi).Le donazioni ci aiutano a mantenere costante e curata la produzione di fanzine.": "<strong>Ĉu vi volas subteni la projekton?</strong><br>Ĝis nun estas 6 numeroj, kiujn vi povas ricevi papere per donaco surloke aŭ kiel pdf per la ligilo en la biografio (ko-fi).<br>La donacoj helpas nin daŭrigi kaj zorgi la produktadon de la fanzino.",
 "Entra nel nostro canale Telegram per non perderti nessun aggiornamento.": "Aliĝu al nia <a href=\"https://t.me/DuoCaneRawPoetry?utm_source=ig&amp;utm_medium=social&amp;utm_content=link_in_bio\" rel=\"noopener\" target=\"_blank\">Telegram-kanalo</a> por ne maltrafi novaĵojn.",
 "canale Telegram": "Telegram-kanalo",
 "III round: martedì 1 dicembre 2026": "Tria rondo: mardo, 1 decembro 2026",
 "Scadenza: 15 novembre 2026": "Limdato: 15 novembro 2026",
 "TORNEO DI POETRY SLAMBar Croazia x FARMOPEN CALL || MARTEDÌ 1 DICEMBRE 2026": "POETRY SLAM-TURNIRO<br>Bar Croazia x FARM<br>MALFERMA ALVOKO || MARDO, 1 DECEMBRO 2026",
 "Da ottobre inizia un nuovo torneo di Poetry Slam a Bologna, presso FARM, in Sant’Isaia 57/D!": "Ekde oktobro komenciĝas nova Poetry Slam-turniro en Bolonjo, ĉe FARM, en Sant’Isaia 57/D!",
 "Tramite il form che trovi qui sotto puoi candidarti per partecipare al III round che si terrà MARTEDÌ 1 DICEMBRE 2026 alle 20.30.": "Per la formularo ĉi-sube vi povas kandidatiĝi por partopreni la trian rondon, kiu okazos MARDON, 1 DECEMBRO 2026, je la 20.30.",
 "Il Poetry Slam è una gara di poesia performativa, dove 6 performers si sfidano tra loro in due manches e una finale.": "Poetry Slam estas konkurso de prezentata poezio, en kiu 6 prezentantoj konkuras en du vicoj kaj finalo.",
 "Una giuria popolare di 5 persone vota da 1 a 10 ogni performance, determinando due persone che si qualificano alla finale di torneo in data 19 gennaio 2027.Lo Slam è parte del circuito L.I.P.S. (Lega Italiana di Poetry Slam).": "Popola ĵurio el 5 personoj voĉdonas de 1 ĝis 10 por ĉiu prezentado, elektante du personojn, kiuj kvalifikiĝas por la turnira finalo de la 19-a de januaro 2027.<br>La Slam estas parto de la cirkvito L.I.P.S. (Itala Ligo de Poetry Slam).",
 "Per partecipare, è necessario rispettare poche e semplici regole:": "Por partopreni, necesas respekti kelkajn simplajn regulojn:",
 "i pezzi devono essere originali, quindi scritti da chi li performa;": "la tekstoj devas esti originalaj, do verkitaj de tiu, kiu prezentas ilin;",
 "si possono usare solo corpo e voce, niente oggetti o vestiti di scena;": "oni rajtas uzi nur korpon kaj voĉon, neniujn objektojn aŭ scenajn vestojn;",
 "ogni performer ha tre minuti di tempo sul palco.": "ĉiu prezentanto havas tri minutojn sur la scenejo.",
 "Per ogni data si qualificano 2 tra le performer con il punteggio più alto, le quali accederanno alla finale di torneo in data MARTEDÌ 19 GENNAIO 2027.Chi vince la finale di torneo accede alle finali regionali Emilia Romagna 2026, del circuito L.I.P.S. Puoi trovare più informazioni sul sito della Lega Italiana di Poetry Slam.": "Ĉe ĉiu dato kvalifikiĝas la 2 prezentantoj kun la plej alta poentaro, kiuj iros al la turnira finalo de MARDO, 19 JANUARO 2027.<br>Kiu venkas en la turnira finalo, iras al la regionaj finaloj de Emilia-Romanjo 2026 de la cirkvito L.I.P.S. Pliajn informojn vi trovos en la <a href=\"https://www.lipslam.it/\" rel=\"noopener\" target=\"_blank\">retejo de la Itala Ligo de Poetry Slam</a>.",
 "sito della Lega Italiana di Poetry Slam": "retejo de la Itala Ligo de Poetry Slam",
 "Nel caso venissi selezionata per partecipare, ti informeremo tramite il numero di telefono o il social che hai inserito.": "Se vi estos elektita por partopreni, ni informos vin per la telefonnumero aŭ la socia reto, kiun vi indikis.",
 "Resta aggiornatə sui social, Instagram e Facebook, e se sei interessata anche ai nostri eventi fuori dallo slam entra nel nostro canale Telegram.": "Restu informita en la sociaj retoj, <a href=\"https://www.instagram.com/barcroazia/\" rel=\"noopener\" target=\"_blank\">Instagram</a> kaj <a href=\"https://www.facebook.com/BarCroazia/\" rel=\"noopener\" target=\"_blank\">Facebook</a>, kaj se vin interesas ankaŭ niaj eventoj ekster la slam, aliĝu al nia <a href=\"https://t.me/DuoCaneRawPoetry?utm_source=ig&amp;utm_medium=social&amp;utm_content=link_in_bio\" rel=\"noopener\" target=\"_blank\">Telegram-kanalo</a>."
};
window.LINGUE_EO_FRASI = [["Prossimo Raw Poetry", "Venonta Raw Poetry"], ["Siamo in piazza adesso", "Ni estas en la placo nun"], ["Scopri: ", "Malkovru: "], ["Scopri poeta", "Malkovru poeton"], ["Guarda tutte le foto", "Vidu ĉiujn fotojn"], ["Seleziona una foto", "Elektu foton"], ["foto in arrivo", "fotoj baldaŭ"], ["Scrivici una mail", "Skribu al ni retleteron"], ["Copia la mail", "Kopiu la retadreson"], ["Copiato!", "Kopiita!"], ["con oggetto", "kun la temo"], ["Sasso", "Ŝtono"], ["Carta", "Papero"], ["Forbici", "Tondilo"], ["Tocca la foto per ingrandirla", "Tuŝu la foton por pligrandigi ĝin"], ["Tocca la locandina per ingrandirla", "Tuŝu la afiŝon por pligrandigi ĝin"]];
