/* ==========================================================
   "SCOPRI POETA" — elenco di poeti e poetesse
   ----------------------------------------------------------
   A ogni apertura della pagina il sito ne sceglie uno a caso,
   mostra il nome nell'etichetta ("scopri poeta: Alda Merini")
   e porta alla sua pagina di Wikipedia in italiano (se la pagina
   italiana non c'è, a quella inglese).

   Per AGGIUNGERE un nome: scrivilo tra virgolette, come gli
   altri, seguito da una virgola. Per TOGLIERLO: cancella la riga.
   ========================================================== */

window.POETI = [
  "Alda Merini",
  "Antonia Pozzi",
  "Amelia Rosselli",
  "Sibilla Aleramo",
  "Ada Negri",
  "Vittoria Colonna",
  "Gaspara Stampa",
  "Cristina Campo",
  "Patrizia Cavalli",
  "Maria Luisa Spaziani",
  "Biancamaria Frabotta",
  "Dacia Maraini",
  "Franca Mancinelli",
  "Vivian Lamarque",
  "Patrizia Valduga",
  "Jolanda Insana",
  "Margherita Guidacci",
  "Antonella Anedda",
  "Mariangela Gualtieri",
  "Elsa Morante",
  "Grazia Deledda",
  "Lalla Romano",
  "Maria Grazia Calandrone",
  "Chandra Livia Candiani",
  "Rosita Copioli",
  "Silvia Bre",
  "Elisa Biagini",
  "Amalia Guglielminetti",
  "Emily Dickinson",
  "Sylvia Plath",
  "Anne Sexton",
  "Saffo",
  "Wisława Szymborska",
  "Anna Achmatova",
  "Marina Cvetaeva",
  "Elizabeth Bishop",
  "Adrienne Rich",
  "Louise Glück",
  "Audre Lorde",
  "Maya Angelou",
  "Christina Rossetti",
  "Elizabeth Barrett Browning",
  "Edith Södergran",
  "Ingeborg Bachmann",
  "Else Lasker-Schüler",
  "Nelly Sachs",
  "Gabriela Mistral",
  "Alfonsina Storni",
  "Alejandra Pizarnik",
  "Rosario Castellanos",
  "Forough Farrokhzad",
  "Louise Labé",
  "Marceline Desbordes-Valmore",
  "Anna de Noailles",
  "Karin Boye",
  "Tove Ditlevsen",
  "Amy Lowell",
  "Hilda Doolittle",
  "Gwendolyn Brooks",
  "Amrita Pritam",
  "Kamala Das",
  "June Jordan",
  "Denise Levertov",
  "Rita Dove",
  "Anne Carson",
  "Carol Ann Duffy",
  "Natasha Trethewey",
  "Tracy K. Smith",
  "Louise Bogan",
  "Marianne Moore",
  "Edna St. Vincent Millay",
  "Sara Teasdale",
  "Anna Świrszczyńska",
  "Ana Blandiana",
  "Nina Cassian",
  "Warsan Shire",
  "Claudia Rankine",
  "Jorie Graham",
  "Sharon Olds",
  "Carolyn Forché",
  "Lucille Clifton",
  "Nikki Giovanni",
  "Sonia Sanchez",
  "Marilyn Hacker",
  "Eavan Boland",
  "Stevie Smith",
  "Kathleen Jamie",
  "Jackie Kay",
  "Bella Achmadulina",
  "Vera Pavlova",
  "Yosano Akiko",
  "Fadwa Tuqan",
  "Nazik al-Mala'ika",
  "Delmira Agustini",
  "Juana de Ibarbourou",
  "Julia de Burgos",
  "Claribel Alegría",
  "Sor Juana Inés de la Cruz",
  "Cecília Meireles",
  "Hilda Hilst",
  "Vittoria Aganoor",
  "Alba de Céspedes",
  "Giulia Niccolai",
  "Nadia Campana",
  "Cristina Annino",
  "Bianca Tarozzi",
  "Rossana Ombres",
  "Fernanda Romagnoli",
  "Alba Donati",
  "Anna Maria Ortese",
  "Renée Vivien",
  "Andrée Chedid",
  "Anne Hébert",
  "Marie Noël",
  "Louise de Vilmorin",
  "Rosalía de Castro",
  "Idea Vilariño",
  "Blanca Varela",
  "Olga Orozco",
  "Gioconda Belli",
  "Elvira Sastre",
  "Chantal Maillard",
  "Florbela Espanca",
  "Sophia de Mello Breyner Andresen",
  "Adélia Prado",
  "Ana Cristina César",
  "Cora Coralina",
  "Zinaida Gippius",
  "Yunna Morits",
  "Halina Poświatowska",
  "Maria Pawlikowska-Jasnorzewska",
  "Inger Christensen",
  "Pia Tafdrup",
  "Sonja Åkesson",
  "Marie Under",
  "Simin Behbahani",
  "Suheir Hammad",
  "Rupi Kaur",
  "Sarojini Naidu",
  "Toru Dutt",
  "Meena Kandasamy",
  "Ono no Komachi",
  "Izumi Shikibu",
  "Machi Tawara",
  "Hiromi Itō",
  "Li Qingzhao",
  "Xi Xi",
  "Zhai Yongming",
  "Noémia de Sousa",
  "Lorna Goodison",
  "Olive Senior",
  "Dionne Brand",
  "Margaret Atwood",
  "Lorna Crozier",
  "Judith Wright",
  "Gwen Harwood",
  "Dorothy Hewett",
  "Fleur Adcock",
  "Anne Bradstreet",
  "Phillis Wheatley",
  "Emily Brontë",
  "Charlotte Mew",
  "Edith Sitwell",
  "Vita Sackville-West",
  "Denise Riley",
  "Alice Oswald",
  "Jo Shapcott",
  "Wendy Cope",
  "Ruth Padel",
  "Jean 'Binta' Breeze",
  "Grace Nichols",
  "Patience Agbabi",
  "Erica Jong",
  "Diane di Prima",
  "Anne Waldman",
  "Alice Notley",
  "Eileen Myles",
  "Ada Limón",
  "Joy Harjo",
  "Kay Ryan",
  "Mary Oliver",
  "Louise Erdrich",
  "Naomi Shihab Nye",
  "Marge Piercy",
  "Anne Stevenson",
  "Alicia Ostriker",
  "Muriel Rukeyser",
  "May Sarton",
  "Amy Clampitt",
  "Jean Valentine",
  "Brenda Hillman",
  "Rae Armantrout",
  "Lyn Hejinian",
  "Susan Howe",
  "Fanny Howe",
  "C.D. Wright",
  "Alice Fulton",
  "Sarah Kirsch",
  "Rose Ausländer",
  "Hilde Domin"
];
